export const SET_USER = "SET_USER";
export const UPDATE_LOGGED_IN_STATUS = "UPDATE_LOGGED_IN_STATUS";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";

export const UPDATE_USER_PLAYLISTS = "UPDATE_USER_PLAYLISTS";